// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// plsStep05Cpp
List plsStep05Cpp(const arma::mat& S, arma::mat lambda, arma::mat gamma, arma::mat C, arma::mat SC, const List& indsLvs, const arma::uvec& lvCol, const arma::uvec& modeB, const arma::umat& preds, const arma::umat& succs, arma::vec outerWeights, const double tol, const int maxIter);
RcppExport SEXP _plssem_plsStep05Cpp(SEXP SSEXP, SEXP lambdaSEXP, SEXP gammaSEXP, SEXP CSEXP, SEXP SCSEXP, SEXP indsLvsSEXP, SEXP lvColSEXP, SEXP modeBSEXP, SEXP predsSEXP, SEXP succsSEXP, SEXP outerWeightsSEXP, SEXP tolSEXP, SEXP maxIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SC(SCSEXP);
    Rcpp::traits::input_parameter< const List& >::type indsLvs(indsLvsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lvCol(lvColSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type modeB(modeBSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type preds(predsSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type succs(succsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type outerWeights(outerWeightsSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxIter(maxIterSEXP);
    rcpp_result_gen = Rcpp::wrap(plsStep05Cpp(S, lambda, gamma, C, SC, indsLvs, lvCol, modeB, preds, succs, outerWeights, tol, maxIter));
    return rcpp_result_gen;
END_RCPP
}
// plsStep6Cpp
Rcpp::List plsStep6Cpp(const arma::mat& X, const arma::mat& W, const arma::umat& prodElems, const arma::uvec& prodCol, const bool doStandardise);
RcppExport SEXP _plssem_plsStep6Cpp(SEXP XSEXP, SEXP WSEXP, SEXP prodElemsSEXP, SEXP prodColSEXP, SEXP doStandardiseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type prodElems(prodElemsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type prodCol(prodColSEXP);
    Rcpp::traits::input_parameter< const bool >::type doStandardise(doStandardiseSEXP);
    rcpp_result_gen = Rcpp::wrap(plsStep6Cpp(X, W, prodElems, prodCol, doStandardise));
    return rcpp_result_gen;
END_RCPP
}
// ordinalizeCpp
Rcpp::IntegerVector ordinalizeCpp(const Rcpp::NumericVector& x, Rcpp::NumericVector probs);
RcppExport SEXP _plssem_ordinalizeCpp(SEXP xSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(ordinalizeCpp(x, probs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_plssem_plsStep05Cpp", (DL_FUNC) &_plssem_plsStep05Cpp, 13},
    {"_plssem_plsStep6Cpp", (DL_FUNC) &_plssem_plsStep6Cpp, 5},
    {"_plssem_ordinalizeCpp", (DL_FUNC) &_plssem_ordinalizeCpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_plssem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
