// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ordinalizeVectorCpp
Rcpp::IntegerVector ordinalizeVectorCpp(const Rcpp::NumericVector& x, Rcpp::NumericVector probs);
RcppExport SEXP _plssem_ordinalizeVectorCpp(SEXP xSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(ordinalizeVectorCpp(x, probs));
    return rcpp_result_gen;
END_RCPP
}
// estimatePLS_Step0_5_Cpp
Rcpp::List estimatePLS_Step0_5_Cpp(arma::mat lambda, arma::mat gamma, arma::mat S, arma::mat C, arma::mat SC, const Rcpp::List& R_IndsIdxLVs, const arma::uvec& lvColIdx, const arma::uvec& modeB, const arma::umat& preds, const arma::umat& succs, const double tolerance, const int maxiter);
RcppExport SEXP _plssem_estimatePLS_Step0_5_Cpp(SEXP lambdaSEXP, SEXP gammaSEXP, SEXP SSEXP, SEXP CSEXP, SEXP SCSEXP, SEXP R_IndsIdxLVsSEXP, SEXP lvColIdxSEXP, SEXP modeBSEXP, SEXP predsSEXP, SEXP succsSEXP, SEXP toleranceSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SC(SCSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type R_IndsIdxLVs(R_IndsIdxLVsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lvColIdx(lvColIdxSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type modeB(modeBSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type preds(predsSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type succs(succsSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(estimatePLS_Step0_5_Cpp(lambda, gamma, S, C, SC, R_IndsIdxLVs, lvColIdx, modeB, preds, succs, tolerance, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// estimatePLS_Step6_Cpp
Rcpp::List estimatePLS_Step6_Cpp(const arma::mat& X, const arma::mat& W, const Rcpp::List& prodElemsIdx, const arma::uvec& prodColIdx, const bool standardize);
RcppExport SEXP _plssem_estimatePLS_Step6_Cpp(SEXP XSEXP, SEXP WSEXP, SEXP prodElemsIdxSEXP, SEXP prodColIdxSEXP, SEXP standardizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prodElemsIdx(prodElemsIdxSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type prodColIdx(prodColIdxSEXP);
    Rcpp::traits::input_parameter< const bool >::type standardize(standardizeSEXP);
    rcpp_result_gen = Rcpp::wrap(estimatePLS_Step6_Cpp(X, W, prodElemsIdx, prodColIdx, standardize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_plssem_ordinalizeVectorCpp", (DL_FUNC) &_plssem_ordinalizeVectorCpp, 2},
    {"_plssem_estimatePLS_Step0_5_Cpp", (DL_FUNC) &_plssem_estimatePLS_Step0_5_Cpp, 12},
    {"_plssem_estimatePLS_Step6_Cpp", (DL_FUNC) &_plssem_estimatePLS_Step6_Cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_plssem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
