PlsModel <- function(matrices         = list(),
                     data             = matrix(),
                     info             = list(),
                     thresholdStruct  = ThresholdStruct(),
                     glsPathModel     = GlsPathModel(),
                     status           = list(),
                     params           = list(),
                     fit              = list(),
                     fitConsistent    = list(),
                     fitUncorrected   = list(),
                     factorScores     = NULL,
                     parTableInput    = data.frame(),
                     higherOrderModel = NULL,
                     combinedModel    = NULL,
                     parTable         = NULL,
                     boot             = list()) {

  methods::new("PlsModel",
    matrices         = matrices,
    data             = data,
    info             = info,
    thresholdStruct  = thresholdStruct,
    glsPathModel     = glsPathModel,
    status           = status,
    params           = params,
    fit              = fit,
    fitConsistent    = fitConsistent,
    fitUncorrected   = fitUncorrected,
    factorScores     = factorScores,
    parTableInput    = parTableInput,
    higherOrderModel = higherOrderModel,
    combinedModel    = combinedModel,
    parTable         = parTable,
    boot             = boot
  )
}


PlsMultilevelModel <- function(level.1         = PlsModel(),
                               level.2         = PlsModel(),
                               info            = list(),
                               data            = matrix(),
                               thresholdStruct = ThresholdStruct(),
                               status          = list(),
                               params          = list(),
                               fit             = list(),
                               factorScores    = list(),
                               parTableInput   = data.frame(),
                               parTable        = NULL,
                               boot            = list()) {

  methods::new("PlsMultilevelModel",
    level.1         = level.1,
    level.2         = level.2,
    info            = info,
    data            = data,
    thresholdStruct = thresholdStruct,
    status          = status,
    params          = params,
    fit             = fit,
    factorScores    = factorScores,
    parTableInput   = parTableInput,
    parTable        = parTable,
    boot            = boot
  )
}
