# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

plsStep05Cpp <- function(S, lambda, gamma, C, SC, indsLvs, lvCol, modeB, preds, succs, outerWeights, tol, maxIter) {
    .Call(`_plssem_plsStep05Cpp`, S, lambda, gamma, C, SC, indsLvs, lvCol, modeB, preds, succs, outerWeights, tol, maxIter)
}

plsStep6Cpp <- function(X, W, prodElems, prodCol, doStandardise) {
    .Call(`_plssem_plsStep6Cpp`, X, W, prodElems, prodCol, doStandardise)
}

ordinalizeCpp <- function(x, probs) {
    .Call(`_plssem_ordinalizeCpp`, x, probs)
}

