# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ordinalizeVectorCpp <- function(x, probs) {
    .Call(`_plssem_ordinalizeVectorCpp`, x, probs)
}

estimatePLS_Step0_5_Cpp <- function(lambda, gamma, S, C, SC, R_IndsIdxLVs, lvColIdx, modeB, preds, succs, tolerance, maxiter) {
    .Call(`_plssem_estimatePLS_Step0_5_Cpp`, lambda, gamma, S, C, SC, R_IndsIdxLVs, lvColIdx, modeB, preds, succs, tolerance, maxiter)
}

estimatePLS_Step6_Cpp <- function(X, W, prodElemsIdx, prodColIdx, standardize) {
    .Call(`_plssem_estimatePLS_Step6_Cpp`, X, W, prodElemsIdx, prodColIdx, standardize)
}

